version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_livecode
      MYSQL_USER: user_livecode
      MYSQL_PASSWORD: pass_livecode
      MYSQL_DATABASE: db_livecode
    networks:
      - backend
    volumes:
      - ./user-data/mariadb/db-data:/var/lib/mysql
      - ./user-data/mariadb/db-src:/docker-entrypoint-initdb.d
    container_name: livecode-db

  livecode:
    build: ./livecode-centos7-httpd
    volumes:
      - ./user-data/html:/var/www/html
    networks:
      - frontend
      - backend
    container_name: livecode-app

  proxy:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    networks:
      - frontend
    container_name: livecode-proxy

networks:
  frontend:
  backend:
